seungdo1234/A15_SpartaRPG

Scripts/GameData/Enums.cs, Scripts/GameData/ItemData.cs, Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs, Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/GamePlay/Screen/Screen.cs, Scripts/GamePlay/Screen/ShopScreen.cs, Scripts/Manager/ItemDataManager.cs
Player, Item 클래스 필드 변수 자동 구현 프로퍼티로 수정
=> :zap:  프로퍼티 수정

Scripts/GameData/Player.cs, Scripts/GameData/Unit.cs
Unit이 공격하는 최종 데미지만 외부에서 컨트롤 가능하도록 만들고
회피 여부를 확인할 수 있도록 했습니다.
Unit 및 Player Attack, IsDamaged(기존 OnDamaged) 변경
IsDamaged 반환타입 void > bool 로 회피여부 확인 및 virtual 추가
Attack 반환 타입 void > int로 변경
=> :art: Unit 및 Player 공격 피격 메소드 변경

Scripts/GameData/Player.cs, Scripts/GameData/Unit.cs
Unit Random protected로 변경 및 Player중복 제거
=> chore: random 접근자 변경

Scripts/GameData/DungeonData.cs, Scripts/GameData/Enums.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/DungeonScreen.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/GameManager.cs
DungeonManager(던전 보상 및 던전 관리 클래스) DungeonData 클래스를 상속 받게함.
DungeonManager 추가 및 GameManager 프로퍼티 수정
=> 🎨 DungeonManager 추가 및 GameManager 프로퍼티 수정

Scripts/GameData/Enums.cs, Scripts/GameData/ItemData.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs, Scripts/Manager/DungeonManager.cs
던전 결과 창 뼈대 개발
추후에 전투 완성 시 수정 예정
=> ✨  던전 결과 창 뼈대 개발

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/ClassSelectionScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs, Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/GamePlay/Screen/StatusScreen.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/ItemDataManager.cs
직업 별 능력치 적용/상태창 표시/ 경험치 상승/ PlayerClass 변수 이름 수정
Player 클래스의 아이템 획득 함수 분리  (상점 구매, 던전 드랍 아이템)
=> :art: 플레이어 레벨 및 직업 관련 로직 수정

Scripts/GameData/Player.cs, Scripts/GameData/SkillData.cs, Scripts/GameData/Unit.cs, Scripts/GameData/WarriorSkills.cs
OnDamaged 를 Attack 내부에서 처리
Attack 반환값으로 크리 여부 반환
=> :art: 공격/방어 로직 변경

Scripts/GameData/Enums.cs, Scripts/GameData/Player.cs, Scripts/GameData/SkillData.cs, Scripts/GameData/Skills/CrisisEvasion.cs, Scripts/GameData/Unit.cs, Scripts/GameData/WarriorSkills.cs, Scripts/GamePlay/Screen/ClassSelectionScreen.cs, Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/Manager/SkillDataManager.cs, TextRPG.csproj
PlayerClass > UnitType으로 Enum변경
SkillDataManager 싱글톤 클래스 추가
Skill 및 공격 로직 변경
=> :art: PlayerClass 이름 변경 및 스킬 로직 변경

SaveData/Enemy.json, Scripts/GameData/Enemy.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/EnemyDataManager.cs
데이터를 .json파일을 통해 불러오기
메인: SaveData/Enemy.json파일 추가 및 형식에 맞게 일부 생성자 수정.
chore: Enemy의 스킬리스트 초기화(인스턴스 생성)
chore: EnemyDataManager의 Init함수 위치 변경
DungeonManager.cs
Enemy.cs
EnemyDataManager.cs
파일 추가
=> :zap: Enemy 데이터 json으로 불러오기

Scripts/GameData/Enums.cs, Scripts/GameData/ItemData.cs, Scripts/GamePlay/Screen/ClassSelectionScreen.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/InventoryScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs, Scripts/GamePlay/Screen/ShopScreen.cs, Scripts/Manager/ItemDataManager.cs, Scripts/System/SaveSystem.cs
ItemDataManager클래스의 플레이어, 상점 아이템 리스트 프로퍼티로 변경
ItemDataManager 클래스 안의 불필요한 함수들 제거
=> :zap:플레이어, 상점 아이템 리스트 프로퍼티로 변경

Scripts/GameData/Enemy.cs, Scripts/Manager/EnemyDataManager.cs
=> :bug: Enemy 깊은복사

Scripts/GameData/Quest.cs, Scripts/Manager/EnemyDataManager.cs, Scripts/Manager/QuestManger.cs
=> :bug: 몬스터 리스트 초기화문제

SaveData/Skills.json, Scripts/GameData/DungeonData.cs, Scripts/GameData/Enums.cs, Scripts/GameData/ItemData.cs, Scripts/GameData/Player.cs, Scripts/GameData/SkillData.cs, Scripts/GameData/Skills/Assassination.cs, Scripts/GameData/Skills/ChainLighting.cs, Scripts/GameData/Skills/WeaknessSniping.cs, Scripts/GameData/Unit.cs, Scripts/GamePlay/Screen/ClassSelectionScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs, Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/GamePlay/Screen/Screen.cs, Scripts/GamePlay/Screen/ShopScreen.cs, Scripts/GameProgram.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/SkillDataManager.cs
열거형선언명 앞에 E 추가
SkillDataManager 싱글톤 구현 및 Json 데이터 Load구현
플레이어 스킬 구현
=> feat : 플레이어 스킬 추가

Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/Manager/ItemDataManager.cs
상점 구매 창에서 아이템 리스트 리롤 할 수 있도록 개발
=> :sparkles:  상점 리롤 개발

SaveData/ItemData.json, Scripts/GameData/Enums.cs, Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs
장비 타입 증가로 인한 장비 장착 및 판매 로직 변경
BitMasking을 이용한 EquipFlag를 통해 장비 착용 여부 확인
장비 판매 및 장착 로직 변경
=> 🎨 : 장비 장착 기능 개선

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs, Scripts/Manager/DungeonManager.cs
=> 🎨 ⚡  전투, 전투 결과창 연결

Scripts/GameData/SkillData.cs, Scripts/GameData/Skills/Assassination.cs, Scripts/GameData/Unit.cs
단일 <> 멀티 계수 뒤바뀐거 정상화
Unit 내부 함수에 방어무시공격 함수 추가
=> 🎨  : 스킬 계수 수정 및 방어무시공격 로직추가

Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs
예외 처리 추가,  멀티 타겟 스킬 사용시 지정 타겟 포함하여 피해를 입히도록 수정
=> 🎨  전투 예외 처리 및 멀티 타겟 수정

Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/Manager/DungeonManager.cs
몬스터 소환코드가 2개 연속으로 되어 있어 수정함.
DungeonManger의 GetMonsterEncount랑 EnemyDataManager의 GetSpawnMonsters랑 같은 기능임.
=> 🎨 중복된 코드 수정

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/InventoryScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs, Scripts/Manager/ItemDataManager.cs, Scripts/System/SaveSystem.cs
플레이어 장비 아이템 리스트
ItemDataManager -> Player로 이동
=> :art: 플레이어 보유 아이템 리스트 리팩토링

Scripts/GameData/Player.cs, Scripts/Manager/ItemDataManager.cs
=> 🐛 상점 장비 아이템 중복 등장 수정

SaveData/QuestSave.json, Scripts/GamePlay/Screen/QuestScreen.cs, Scripts/Manager/QuestManager.cs
=> [refactor] QuestSave 네임드 튜플로 바꾸기

Scripts/GameData/Enums.cs, Scripts/GamePlay/Screen/EquipScreen.cs, Scripts/GamePlay/Screen/InventoryScreen.cs, Scripts/GamePlay/Screen/LobbyScreen.cs, Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/GamePlay/Screen/QuestScreen.cs, Scripts/GamePlay/Screen/Screen.cs, Scripts/GamePlay/Screen/StatusScreen.cs
시스템 메세지 타입을 위한 Enum EMessageType 추가
던전입장, 상점을 제외한 콘솔화면 리프레시 개선 및 시스템 메세지 출력 변경
=> 🎨 : 시스템메세지 타입 Enum 추가 및 스크린 리프레시 개선

Scripts/GamePlay/Screen/StatusScreen.cs
=> 🎨 : 상태보기에서 아이템 추가 능력치 표시

Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/System/SaveSystem.cs
=> :zap: 로그인 메커니즘 변경

Scripts/GamePlay/Screen/LoginScreen.cs
=> 🩹 스크린의 SystemMessageText 로그인스크린에 적용

Scripts/GamePlay/Screen/LoginScreen.cs, Scripts/GamePlay/Screen/QuestScreen.cs, Scripts/System/SaveSystem.cs
=> :fire: 클래스 선택창 다시 삽입

Scripts/GameData/Enums.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/Screen.cs
=> 🩹 시스템에러 메세지 타입 추가

Scripts/GameData/Items/ConsumableItem.cs, Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/InventoryScreen.cs
소비 아이템 사용 함수 생성
인벤토리에 소비 아이템 표시
플레이어 회복 함수 생성
=> 🎨  소비 아이템 사용 함수, 인벤토리 표시

SaveData/Skills.json, Scripts/GameData/Boss.cs, Scripts/GameData/Enums.cs, Scripts/GameData/Skills/BloodDrain.cs, Scripts/GameData/Skills/CallOfDeath.cs, Scripts/GameData/Skills/DemonClaw.cs, Scripts/GamePlay/Screen/ClassSelectionScreen.cs, Scripts/Manager/EnemyDataManager.cs
보스 컨텐츠 추가에 따른 변경
보스 추가에 따른
Boss 클래스 추가
Enum EUnitType에 Boss추가
보스 스킬 클래스 3개 추가
유닛타입 증가로 인한 직업 선택 화면 for문 인덱스 -1
EnemyDataManager 보스 객체 생성 기능 추가
=> ✨  : 보스 클래스,UnitType,스킬 추가

Scripts/GameData/Items/Item.cs, Scripts/GamePlay/Screen/InventoryScreen.cs, Scripts/GamePlay/Screen/ItemBuyScreen.cs, Scripts/GamePlay/Screen/ItemSellScreen.cs, Scripts/GamePlay/Screen/Screen.cs, Scripts/GamePlay/Screen/ShopScreen.cs
=> 🎨 아이템 등급 색깔 적용

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/QuestScreen.cs
포션 사용 DungeonBattle에서 구현
DungeonBattle최하단
private ConsumableItem SelectPotion() 메서드 구현
그 후 private int PlayerAction(Enemy enemy) 메서드 case 3에 선택지로 넣음
=> ✨ 포션 사용 DungeonBattle에서 구현

Scripts/Manager/QuestManager.cs
=> [feat] StoryQuest 게임진행에 따른 자동 업데이트

Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/EnemyDataManager.cs
경험치 보상과 결과 창엣서 체력, 경험치 표기 추가
소비 아이템 보상이 안나올 때 Null 참조 오류나는 거 해결
=> :sparkles: :bug: 경험치 보상 및 표기, 버그 수정

Scripts/GamePlay/Screen/CreditScreen.cs
=> :sparkles: 크레딧 스크린

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/StatusScreen.cs
=> 🎨 : 상태보기 스킬 정보 출력

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs, Scripts/Manager/DungeonManager.cs, Scripts/Manager/EnemyDataManager.cs
1. 전투 계속시 로비로 가는 현상 해결, 
2. DungeonBattleScreen에 있는 CheckForDifficulty에서 input의 자료형 변경
1. DungeonResultScreen 클래스 코드 50줄에 새 if구문으로 다음 배틀 진행하도록 변경
2. DungeonBattleScreen 클래스에 있는 CheckForDifficulty에서 string형식이던 input, int형식으로 변경 및 예외 처리 완료
DungeonResultScreen 에 있는 ScreenOn함수에 새 if구문 추가
DungeonBattleScreen 에 있는 CheckForDifficulty 함수 코드 변경
=> 🐛 전투 계속시 로비로 가는 현상 해결, CheckForDifficulty에서 input의 자료형 변경

SaveData/Skills.json, Scripts/GameData/Debuffs/Burning.cs, Scripts/GameData/Debuffs/Poisoning.cs, Scripts/GameData/Enemy.cs, Scripts/GameData/Skill.cs, Scripts/GameData/Skills/Bite.cs, Scripts/GameData/Skills/BlackOut.cs, Scripts/GameData/Skills/DeathSentence.cs, Scripts/GameData/Skills/DemonClaw.cs, Scripts/GameData/Skills/FuryOfBeast.cs, Scripts/GameData/Skills/Inferno.cs, Scripts/GameData/Skills/LifeDrain.cs, Scripts/GameData/Skills/Roar.cs, Scripts/GameData/Skills/SongOfSiren.cs, Scripts/GameData/Skills/Venom.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs
몬스터 스킬 추가
몬스터 스킬 10종 구현 및 Skills.json 내용 갱신
Enemy 생성자에 각 레벨 몬스터에 따른 스킬 생성 구현
배틀스크린에 플레이어 디버프 이벤트와 적 스킬 시전 추가
=> ✨  : 몬스터 스킬 추가

Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/QuestScreen.cs, Scripts/Manager/QuestManager.cs
=> :zap: 퀘스트 버그 개선

Scripts/GameData/Skills/BlackOut.cs, Scripts/GameData/Skills/ChainLighting.cs, Scripts/GameData/Skills/Chomp.cs, Scripts/GameData/Skills/CrisisEvasion.cs, Scripts/GameData/Skills/Inferno.cs, Scripts/GameData/Skills/Roar.cs, Scripts/GameData/Skills/SongOfSiren.cs, Scripts/GameData/Skills/Venom.cs, Scripts/GameData/Skills/WeaknessSniping.cs, TextRPG.csproj
스킬 사용으로 상태이상 걸릴 시
대상 > target.Name으로 출력
=> chore : 스킬로 상태이상 시 출력 내용 변경

Scripts/GameData/DungeonData.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/Manager/DungeonManager.cs
=> ⚡  던전 레벨 리팩토링

Scripts/GameData/Player.cs, Scripts/GamePlay/Screen/DungeonBattleScreen.cs, Scripts/GamePlay/Screen/DungeonResultScreen.cs
=> ⚡ 플레이어 레벨 수정 및 결과창 적 숫자 표기 수정

Scripts/GameData/Player.cs, Scripts/GameData/Unit.cs
=> 🎨  : 회피율 재적용

Scripts/GameData/Skills/Assassination.cs
=> chore : 암살스킬 수정
